# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cathedral.v1 import bridge_pb2 as cathedral_dot_v1_dot_bridge__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cathedral/v1/bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CathedralBridgeStub:
    """============================================================
    SERVIÇO PRINCIPAL
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/cathedral.v1.CathedralBridge/Ingest',
                request_serializer=cathedral_dot_v1_dot_bridge__pb2.IngestRequest.SerializeToString,
                response_deserializer=cathedral_dot_v1_dot_bridge__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.RequestGovernance = channel.unary_unary(
                '/cathedral.v1.CathedralBridge/RequestGovernance',
                request_serializer=cathedral_dot_v1_dot_bridge__pb2.GovernanceRequest.SerializeToString,
                response_deserializer=cathedral_dot_v1_dot_bridge__pb2.GovernanceResponse.FromString,
                _registered_method=True)
        self.QueryProvenance = channel.unary_unary(
                '/cathedral.v1.CathedralBridge/QueryProvenance',
                request_serializer=cathedral_dot_v1_dot_bridge__pb2.QueryProvenanceRequest.SerializeToString,
                response_deserializer=cathedral_dot_v1_dot_bridge__pb2.QueryProvenanceResponse.FromString,
                _registered_method=True)


class CathedralBridgeServicer:
    """============================================================
    SERVIÇO PRINCIPAL
    ============================================================
    """

    def Ingest(self, request, context):
        """Envia um lote de eventos de proveniência (design, simulação, mutação, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestGovernance(self, request, context):
        """Consulta síncrona de governança (EthicalGuardian)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryProvenance(self, request, context):
        """Consulta de histórico de proveniência (futuro / opcional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CathedralBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=cathedral_dot_v1_dot_bridge__pb2.IngestRequest.FromString,
                    response_serializer=cathedral_dot_v1_dot_bridge__pb2.IngestResponse.SerializeToString,
            ),
            'RequestGovernance': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestGovernance,
                    request_deserializer=cathedral_dot_v1_dot_bridge__pb2.GovernanceRequest.FromString,
                    response_serializer=cathedral_dot_v1_dot_bridge__pb2.GovernanceResponse.SerializeToString,
            ),
            'QueryProvenance': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryProvenance,
                    request_deserializer=cathedral_dot_v1_dot_bridge__pb2.QueryProvenanceRequest.FromString,
                    response_serializer=cathedral_dot_v1_dot_bridge__pb2.QueryProvenanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cathedral.v1.CathedralBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cathedral.v1.CathedralBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CathedralBridge:
    """============================================================
    SERVIÇO PRINCIPAL
    ============================================================
    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cathedral.v1.CathedralBridge/Ingest',
            cathedral_dot_v1_dot_bridge__pb2.IngestRequest.SerializeToString,
            cathedral_dot_v1_dot_bridge__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestGovernance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cathedral.v1.CathedralBridge/RequestGovernance',
            cathedral_dot_v1_dot_bridge__pb2.GovernanceRequest.SerializeToString,
            cathedral_dot_v1_dot_bridge__pb2.GovernanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryProvenance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cathedral.v1.CathedralBridge/QueryProvenance',
            cathedral_dot_v1_dot_bridge__pb2.QueryProvenanceRequest.SerializeToString,
            cathedral_dot_v1_dot_bridge__pb2.QueryProvenanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
