# Fly.io configuration for XRP X402 Facilitator
app = 'xrp-x402-fac-1758406085'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'
  XRP_NETWORK = 'xrp-testnet'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[machine]
  memory = 256

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1