packages:
  - "facilitator"
  - "servers/*"
  - "clients/*"
  - "fullstack/*"
  - "dynamic_agent"
  - "agent"
  - "mcp-embedded-wallet"
  - "mpc"
  - "discovery"
  - "negotiated-pricing"
  - "../../typescript/packages/*"
