name: Go CI
on:
  pull_request:
    paths:
      - "go/**"
  push:
    branches:
      - main
    paths:
      - "go/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./go

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          working-directory: ./go

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run tests
        run: make test
