name: Publish coinbase-x402 package to NPM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-npm-coinbase-x402:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'npm' || '' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.7.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: ./typescript

      - name: Install and build
        working-directory: ./typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm -r --filter=x402 --filter=@coinbase/x402 run build
      
      - name: Publish coinbase-x402 package
        working-directory: ./typescript/packages/coinbase-x402
        run: |
          # Get package information directly
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          
          echo "Package: $PACKAGE_NAME@$PACKAGE_VERSION"
          
          # Check if running on main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Publishing to NPM (main branch)"
            pnpm publish --provenance --access public
          else
            echo "Dry run only (non-main branch: ${{ github.ref }})"
            pnpm publish --dry-run --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 